"""Replay saved live answers offline and write a separate, privacy-reduced summary."""

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sys
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.evaluation.history import collect_history, replay_case, summarize


def render_markdown(result):
    counts = result["summary"]
    lines = ["# Historical Replay and Evaluation Summary", "", f"Report date: {result['report_date']} (Asia/Shanghai).",
             "", "## Scope", "",
             "Offline replay of preserved real-call artifacts under the current validator. No provider,",
             "database, retriever or workflow execution; no original artifact was modified.",
             "This is validator replay, NOT a test of the new prompt or a new model-quality benchmark.",
             "Duplicate request IDs are counted once; conflicting evidence for the same ID causes failure.",
             "", "## Counts", "",
             f"- Unique historical attempts: {counts['unique_attempts']}; duplicate rows removed: {counts['duplicate_entries_removed']}.",
             f"- Historical outcomes: {counts['historical_status_counts']}.",
             f"- Current replay outcomes: {counts['current_replay_status_counts']}.",
             f"- Historical calls with known usage: {counts['historical_calls_with_known_usage']}.",
             f"- Historical token counters (deduplicated): {counts['historical_token_totals']}.",
             "- New model calls/tokens: 0 / 0. No new provider charges; account billing was not queried.",
             "", "## Per-request Results", "",
             "| Scenario | Request ID | Historical outcome | Current replay | Diagnostic / limitation |",
             "| --- | --- | --- | --- | --- |"]
    for row in result["cases"]:
        diagnostic = row.get("diagnostic") or {}
        detail = " / ".join(str(diagnostic[key]) for key in ("code", "path", "fact_field", "expected", "observed") if key in diagnostic) or row.get("reason", "Narrow checks only")
        lines.append(f"| {row['scenario']} | {row['request_id']} | {row['historical_status']} | {row['replay_status']} | {detail} |")
    lines += ["", "## Latest Preserved Cases", "",
              "Ordering uses first appearance in sorted snapshot artifacts, not verified provider timestamps.",
              "Latest does not mean representative or independently sampled; earlier failures remain above.", ""]
    for scenario, value in counts["latest_preserved_case_by_artifact_order"].items():
        lines.append(f"- {scenario}: historical {value['historical_status']}; current replay {value['replay_status']}; `{value['request_id']}`.")
    lines += ["", "## Interpretation and Gaps", "",
              "- Historical acceptance means the then-current implementation accepted an output, not factual accuracy.",
              "- Missing rejected bodies cannot be replayed or used to establish their failure cause; unavailable is not a pass.",
              "- A historical accepted answer rejected now is a regression check showing stricter validation, not a rewritten historical outcome.",
              "- The saved missing-policy suggestion confuses customer score 85 with the demo threshold 80; current validation rejects it.",
              "- An earlier accepted missing-policy answer still lacks explicit absent-evidence wording; validator acceptance does not resolve that quality gap.",
              "- Extra deterministic policy notices are removed only for model-schema parsing; arbitrary extra fields are still rejected.",
              "- Numeric labels and threshold patterns do not comprehensively verify prose. Suggested hypothetical clauses,",
              "  evidence entailment, regulatory interpretation, boilerplate and missing-policy wording still require review.",
              "- Attack-marker absence in an ordinary case is not an injection test. Preserved injection evidence is reported",
              "  separately; one attack example cannot establish general injection resistance.",
              "- Source artifacts do not contain full prompt provenance. The validator source hash below is replay provenance,",
              "  not proof that these answers were generated by the latest prompt. New-prompt live acceptance remains untested.",
              "- No percentage here should be described as banking accuracy. Fixtures are tiny and selected across changing versions.",
              "- Human analyst sign-off remains pending. Detailed replay JSON has identifiers/diagnostics and stays ignored by Git.",
              "", "## Reproduction", "", "```powershell",
              f".\\.venv\\Scripts\\python.exe scripts/replay_review_history.py --report-date {result['report_date']}",
              "```", "", f"Validator SHA-256: `{result['validator_sha256']}`.",
              "Source artifact hashes and privacy-reduced diagnostics are in `data/evaluations/replay-results.json`.",
              "Only live*.json inputs are read; free simulation results are not mixed into real-call statistics."]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=ROOT / "data/evaluations")
    parser.add_argument("--report-date", default=str(datetime.now(ZoneInfo("Asia/Shanghai")).date()))
    args = parser.parse_args()
    datetime.strptime(args.report_date, "%Y-%m-%d")
    paths = sorted(args.input_dir.glob("live*.json"))
    if not paths:
        raise ValueError("No saved live artifacts; no model calls will be initiated")
    entries, sources, duplicates = collect_history(paths)
    if not entries:
        raise ValueError("No live cases in supplied artifacts")
    rows = [replay_case(entry) for entry in entries]
    result = dict(report_date=args.report_date, created_at=datetime.now(timezone.utc).isoformat(),
                  phase="offline_history_replay", validator_sha256=hashlib.sha256((ROOT / "app/graph/review_explanation.py").read_bytes()).hexdigest(),
                  input_sources=sources, summary=summarize(rows, duplicates), cases=rows)
    # Ensure inputs remained unchanged during this run; never overwrite original live files.
    expected = {source["file"]:source["sha256"] for source in sources}
    for path in paths:
        if path.name in expected and hashlib.sha256(path.read_bytes()).hexdigest() != expected[path.name]:
            raise ValueError("Source changed during replay; summary not written")
    output = ROOT / "data/evaluations"
    output.mkdir(parents=True, exist_ok=True)
    encoded = json.dumps(result, ensure_ascii=False, indent=2)
    snapshot = output / ("replay-" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ") + ".json")
    snapshot.write_text(encoded, encoding="utf-8")
    (output / "replay-results.json").write_text(encoded, encoding="utf-8")
    (ROOT / "docs/historical-replay.md").write_text(render_markdown(result), encoding="utf-8")
    print(json.dumps(result["summary"], ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
